name: Build
on:
  push:
    branches:
      - main
      
permissions:
  contents: write
  pull-requests: write
      
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install -e .
          pip install pytest pytest-cov pytest-asyncio
      
      - name: Run tests with coverage
        continue-on-error: true
        run: |
         PYTHONPATH=. python -m pytest --cov=. --cov-report=xml --cov-report=term
      
      - name: SonarQube Scan
        if: always()
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      
      - name: SonarQube Badge
        if: always()
        uses: jadewon/sonar-badge@v1
        with:
          metrics: 'bugs, code_smells, coverage, duplicated_lines_density, ncloc, sqale_rating, alert_status, reliability_rating, security_hotspots, security_rating, sqale_index, vulnerabilities'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT: Claude-MCP
